Airbyte:
  config:
    custom_api_definition_id: ''
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    postgres_definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
    redshift_definition_id: f7a7d195-377f-cf5b-70a5-be6b819019dc
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://schemapile--github-com-medbounaga-defterp-3-61ba6c452c56-bucket/erp_account.jsonl
    sync_mode: full_refresh_append
    table: erp_account
  - path: s3://schemapile--github-com-medbounaga-defterp-3-61ba6c452c56-bucket/erp_invoice_tax.jsonl
    sync_mode: full_refresh_append
    table: erp_invoice_tax
  - path: s3://schemapile--github-com-medbounaga-defterp-3-61ba6c452c56-bucket/erp_journal_entry.jsonl
    sync_mode: full_refresh_append
    table: erp_journal_entry
  - path: s3://schemapile--github-com-medbounaga-defterp-3-61ba6c452c56-bucket/erp_payment.jsonl
    sync_mode: full_refresh_append
    table: erp_payment
  - path: s3://schemapile--github-com-medbounaga-defterp-3-61ba6c452c56-bucket/erp_purchase_order.jsonl
    sync_mode: full_refresh_append
    table: erp_purchase_order
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - erp_delivery_order_line
    - erp_invoice_payment
    - erp_journal
    - erp_journal_item
    - erp_product
    - erp_product_category
    - erp_tax
flat_files:
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_inventory.csv
  sync_mode: full_refresh_append
  table: erp_inventory
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_invoice.csv
  sync_mode: full_refresh_append
  table: erp_invoice
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_partner.csv
  sync_mode: full_refresh_append
  table: erp_partner
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_product_uom.csv
  sync_mode: full_refresh_append
  table: erp_product_uom
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_product_uom_category.csv
  sync_mode: full_refresh_append
  table: erp_product_uom_category
- format: csv
  path: http://elt-files:8080/schemapile__github_com_medbounaga_defterp_3_61ba6c452c56/erp_purchase_order_line.csv
  sync_mode: full_refresh_append
  table: erp_purchase_order_line
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: schemapile__github_com_medbounaga_defterp_3_61ba6c452c56
    sync_mode: full_refresh_append
    tables:
    - erp_delivery_order
    - erp_sale_order
    - erp_user
postgres:
  config:
    database: schemapile__github_com_medbounaga_defterp_3_61ba6c452c56
    host: elt-postgres
    password: testelt
    port: 5432
    schema: public
    sync_mode: full_refresh_append
    tables:
    - erp_invoice_line
    - erp_sale_order_line
    user: postgres
redshift:
  config:
    access_key_id: ''
    database: ''
    host: ''
    password: ''
    port: 5439
    s3_bucket_name: ''
    s3_bucket_region: ''
    schema: schemapile__github_com_medbounaga_defterp_3_61ba6c452c56
    secret_access_key: ''
    username: ''
