"""Serve generated REST and file fixtures from ``sources_serving.json``.

REST routes return JSON arrays with ``offset`` and ``limit`` pagination. File
routes return generated bytes unchanged. The module uses only the standard
library so it can run in source-service containers.
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import posixpath
import ssl
import urllib.parse
from dataclasses import dataclass
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any, Literal, Mapping


BackendMode = Literal["rest", "files", "both"]


class SourceFixtureError(ValueError):
    """A serving manifest or rendered source fixture is malformed."""


@dataclass(frozen=True)
class Route:
    backend: str
    path: str
    artifact: Path


def _within(root: Path, path: Path) -> Path:
    root = root.resolve()
    candidate = path.resolve()
    if candidate != root and root not in candidate.parents:
        raise SourceFixtureError(f"artifact escapes rendered root: {path}")
    return candidate


def _url_path(value: str) -> str:
    path = urllib.parse.urlparse(value).path
    if not path.startswith("/"):
        path = "/" + path
    return posixpath.normpath(path)


def load_routes(
    manifest_path: Path,
    rendered_root: Path,
    *,
    mode: BackendMode = "both",
) -> dict[str, Route]:
    """Validate and resolve every HTTP route selected by ``mode``."""
    manifest_path = Path(manifest_path)
    rendered_root = Path(rendered_root).resolve()
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SourceFixtureError(f"invalid serving manifest: {manifest_path}") from exc
    tables = manifest.get("tables") if isinstance(manifest, dict) else None
    if not isinstance(tables, dict):
        raise SourceFixtureError("serving manifest has no tables object")
    routes: dict[str, Route] = {}
    for table, raw in sorted(tables.items()):
        if not isinstance(raw, dict):
            raise SourceFixtureError(f"table {table!r} serving entry is not an object")
        backend = str(raw.get("backend") or "")
        if backend == "rest" and mode in ("rest", "both"):
            route = str(raw.get("route") or "")
            rel = str(raw.get("rendered_dir") or "")
            if not route.startswith("/") or not rel:
                raise SourceFixtureError(f"REST table {table!r} has no route/artifact")
            artifact = _within(rendered_root, rendered_root / rel)
            if not artifact.is_dir():
                raise SourceFixtureError(f"REST fixture directory is missing: {artifact}")
            normalized = posixpath.normpath(route)
            if normalized in routes:
                raise SourceFixtureError(f"duplicate HTTP route: {normalized}")
            routes[normalized] = Route(backend, normalized, artifact)
        elif backend == "files" and mode in ("files", "both"):
            url = str(raw.get("url") or "")
            rel = str(raw.get("rendered_file") or "")
            if not url or not rel:
                raise SourceFixtureError(f"file table {table!r} has no URL/artifact")
            artifact = _within(rendered_root, rendered_root / rel)
            if not artifact.is_file():
                raise SourceFixtureError(f"file fixture is missing: {artifact}")
            route = _url_path(url)
            if route in routes:
                raise SourceFixtureError(f"duplicate HTTP route: {route}")
            routes[route] = Route(backend, route, artifact)
    return routes


def read_rest_records(directory: Path) -> list[dict[str, Any]]:
    """Concatenate the page files named by ``index.json`` in exact order."""
    index_path = Path(directory) / "index.json"
    try:
        index = json.loads(index_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise SourceFixtureError(f"invalid REST index: {index_path}") from exc
    pages = index.get("pages") if isinstance(index, dict) else None
    if not isinstance(pages, list) or any(not isinstance(name, str) for name in pages):
        raise SourceFixtureError(f"{index_path}: expected a pages string list")
    rows: list[dict[str, Any]] = []
    for name in pages:
        page_path = _within(Path(directory), Path(directory) / name)
        try:
            page = json.loads(page_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SourceFixtureError(f"invalid REST page: {page_path}") from exc
        records = page.get("data") if isinstance(page, dict) else None
        if not isinstance(records, list) or any(not isinstance(row, dict) for row in records):
            raise SourceFixtureError(f"{page_path}: expected a data object list")
        rows.extend(records)
    expected = index.get("row_count") if isinstance(index, dict) else None
    if not isinstance(expected, int) or expected != len(rows):
        raise SourceFixtureError(
            f"{index_path}: row_count is {expected!r}, rendered pages contain {len(rows)}"
        )
    return rows


def _nonnegative_int(query: Mapping[str, list[str]], key: str, default: int) -> int:
    values = query.get(key)
    if not values:
        return default
    try:
        value = int(values[-1])
    except (TypeError, ValueError) as exc:
        raise SourceFixtureError(f"query parameter {key!r} must be an integer") from exc
    if value < 0:
        raise SourceFixtureError(f"query parameter {key!r} must be non-negative")
    return value


def make_handler(routes: Mapping[str, Route]) -> type[BaseHTTPRequestHandler]:
    """Build a request handler bound to an immutable route mapping."""
    route_map = dict(routes)

    class Handler(BaseHTTPRequestHandler):
        server_version = "ELTTaskgenSource/1"

        def log_message(self, format: str, *args: object) -> None:  # noqa: A002
            # Avoid noisy request logs in solver traces. The HTTP status remains
            # available to Docker health checks and callers.
            return

        def _send(self, *, include_body: bool) -> None:
            parsed = urllib.parse.urlparse(self.path)
            path = posixpath.normpath(parsed.path)
            if path == "/healthz":
                payload = b'{"status":"ok"}\n'
                self.send_response(HTTPStatus.OK)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                if include_body:
                    self.wfile.write(payload)
                return
            route = route_map.get(path)
            if route is None:
                self.send_error(HTTPStatus.NOT_FOUND)
                return
            try:
                if route.backend == "rest":
                    query = urllib.parse.parse_qs(parsed.query, keep_blank_values=True)
                    offset = _nonnegative_int(query, "offset", 0)
                    rows = read_rest_records(route.artifact)
                    limit = _nonnegative_int(
                        query, "limit", max(0, len(rows) - offset)
                    )
                    payload = (
                        json.dumps(
                            rows[offset : offset + limit],
                            separators=(",", ":"),
                            sort_keys=True,
                        )
                        + "\n"
                    ).encode("utf-8")
                    content_type = "application/json"
                else:
                    payload = route.artifact.read_bytes()
                    content_type = (
                        mimetypes.guess_type(route.artifact.name)[0]
                        or "application/octet-stream"
                    )
            except SourceFixtureError as exc:
                self.send_error(HTTPStatus.INTERNAL_SERVER_ERROR, str(exc))
                return
            self.send_response(HTTPStatus.OK)
            self.send_header("Content-Type", content_type)
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            if include_body:
                self.wfile.write(payload)

        def do_GET(self) -> None:  # noqa: N802
            self._send(include_body=True)

        def do_HEAD(self) -> None:  # noqa: N802
            self._send(include_body=False)

    return Handler


def serve(
    manifest_path: Path,
    rendered_root: Path,
    *,
    host: str,
    port: int,
    mode: BackendMode,
    certfile: Path | None = None,
    keyfile: Path | None = None,
) -> None:
    """Serve the rendered population, over TLS when a certificate is supplied."""
    routes = load_routes(manifest_path, rendered_root, mode=mode)
    server = ThreadingHTTPServer((host, int(port)), make_handler(routes))
    if certfile is not None or keyfile is not None:
        if certfile is None or keyfile is None:
            raise ValueError("TLS needs both a certificate and a private key")
        context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        context.load_cert_chain(str(certfile), str(keyfile))
        server.socket = context.wrap_socket(server.socket, server_side=True)
    server.serve_forever()


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--rendered-root", type=Path, required=True)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, required=True)
    parser.add_argument("--backend", choices=("rest", "files", "both"), default="both")
    parser.add_argument("--certfile", type=Path, default=None)
    parser.add_argument("--keyfile", type=Path, default=None)
    args = parser.parse_args(argv)
    serve(
        args.manifest,
        args.rendered_root,
        host=args.host,
        port=args.port,
        mode=args.backend,
        certfile=args.certfile,
        keyfile=args.keyfile,
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
