Airbyte:
  config:
    custom_api_definition_id: ''
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    snowflake_definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://synsql--3d-path-or-motion-tracking--motion-1d4804d88f47-bucket/motion_paths.jsonl
    sync_mode: full_refresh_append
    table: motion_paths
  - path: s3://synsql--3d-path-or-motion-tracking--motion-1d4804d88f47-bucket/steps.jsonl
    sync_mode: full_refresh_append
    table: steps
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - system_settings
    - users
flat_files:
- format: csv
  path: http://elt-files:8080/synsql__3d_path_or_motion_tracking__motion_1d4804d88f47/maintenance_records.csv
  sync_mode: full_refresh_append
  table: maintenance_records
- format: csv
  path: http://elt-files:8080/synsql__3d_path_or_motion_tracking__motion_1d4804d88f47/path_versions.csv
  sync_mode: full_refresh_append
  table: path_versions
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: synsql__3d_path_or_motion_tracking__motion_1d4804d88f47
    sync_mode: full_refresh_append
    tables:
    - access_logs
    - machine_learning_models
    - notifications
    - optimization_results
    - performance_metrics
    - robots
snowflake:
  config:
    account: ''
    database: synsql__3d_path_or_motion_tracking__motion_1d4804d88f47
    password: ''
    role: ''
    schema: AIRBYTE_SCHEMA
    username: ''
    warehouse: ''
