Airbyte:
  config:
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    snowflake_definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://wikidbs--c40096--40096-mattis-mathiesen-filmography-bucket/screenwriter.jsonl
    sync_mode: full_refresh_append
    table: screenwriter
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: wikidbs__c40096__40096_mattis_mathiesen_filmography
    sync_mode: full_refresh_append
    tables:
    - film_industry_professionals
    - filmography_cast_details
    - filmography_details
    - norwegian_filmmakers
snowflake:
  config:
    account: ''
    database: wikidbs__c40096__40096_mattis_mathiesen_filmography
    password: ''
    role: ''
    schema: AIRBYTE_SCHEMA
    username: ''
    warehouse: ''
