Airbyte:
  config:
    custom_api_definition_id: ''
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    postgres_definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    snowflake_definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://dlt--workable-bucket/candidates_offer.jsonl
    sync_mode: full_refresh_append
    table: candidates_offer
  - path: s3://dlt--workable-bucket/jobs_custom_attributes.jsonl
    sync_mode: full_refresh_append
    table: jobs_custom_attributes
  - path: s3://dlt--workable-bucket/jobs_stages.jsonl
    sync_mode: full_refresh_append
    table: jobs_stages
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - members
flat_files:
- format: csv
  path: http://elt-files:8080/dlt__workable/candidates_activities.csv
  sync_mode: full_refresh_append
  table: candidates_activities
- format: csv
  path: http://elt-files:8080/dlt__workable/events.csv
  sync_mode: full_refresh_append
  table: events
- format: csv
  path: http://elt-files:8080/dlt__workable/jobs_questions.csv
  sync_mode: full_refresh_append
  table: jobs_questions
- format: csv
  path: http://elt-files:8080/dlt__workable/jobs_recruiters.csv
  sync_mode: full_refresh_append
  table: jobs_recruiters
- format: csv
  path: http://elt-files:8080/dlt__workable/recruiters.csv
  sync_mode: full_refresh_append
  table: recruiters
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: dlt__workable
    sync_mode: full_refresh_append
    tables:
    - jobs_activities
    - jobs_application_form
    - requisitions
    - stages
postgres:
  config:
    database: dlt__workable
    host: elt-postgres
    password: testelt
    port: 5432
    schema: public
    sync_mode: full_refresh_append
    tables:
    - candidates
    - custom_attributes
    - jobs
    - jobs_members
    user: postgres
snowflake:
  config:
    account: ''
    database: dlt__workable
    password: ''
    role: ''
    schema: AIRBYTE_SCHEMA
    username: ''
    warehouse: ''
