Airbyte:
  config:
    custom_api_definition_id: ''
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    postgres_definition_id: decd338e-5647-4c0b-adf4-da0e75f5a750
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    snowflake_definition_id: 424892c4-daac-4491-b35d-c6688ba547ba
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/billing_address.jsonl
    sync_mode: full_refresh_append
    table: billing_address
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/issue.jsonl
    sync_mode: full_refresh_append
    table: issue
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/menuitem.jsonl
    sync_mode: full_refresh_append
    table: menuitem
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/test_case_multimedia.jsonl
    sync_mode: full_refresh_append
    table: test_case_multimedia
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/test_plan_sprint.jsonl
    sync_mode: full_refresh_append
    table: test_plan_sprint
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/test_plan_sprint_case.jsonl
    sync_mode: full_refresh_append
    table: test_plan_sprint_case
  - path: s3://schemapile--github-com-michalbecko-junopubl-d7c58a4576c5-bucket/user.jsonl
    sync_mode: full_refresh_append
    table: user
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - client
    - issue_multimedia
    - login_picture
    - mailer
    - mailer_default
    - multimedia
    - multimedia_folder
    - user_web_role
flat_files:
- format: csv
  path: http://elt-files:8080/schemapile__github_com_michalbecko_junopubl_d7c58a4576c5/project_role.csv
  sync_mode: full_refresh_append
  table: project_role
- format: csv
  path: http://elt-files:8080/schemapile__github_com_michalbecko_junopubl_d7c58a4576c5/role_privilege.csv
  sync_mode: full_refresh_append
  table: role_privilege
- format: csv
  path: http://elt-files:8080/schemapile__github_com_michalbecko_junopubl_d7c58a4576c5/settings.csv
  sync_mode: full_refresh_append
  table: settings
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: schemapile__github_com_michalbecko_junopubl_d7c58a4576c5
    sync_mode: full_refresh_append
    tables:
    - log
    - mailer_attachment
    - project
    - role
    - tag_test_set
    - test_case_run
    - test_set
    - test_step
postgres:
  config:
    database: schemapile__github_com_michalbecko_junopubl_d7c58a4576c5
    host: elt-postgres
    password: testelt
    port: 5432
    schema: public
    sync_mode: full_refresh_append
    tables:
    - address
    - tag_test_case
    - test_case
    - test_plan
    - test_plan_case
    - test_plan_sprint_case_user
    - test_step_execution
    user: postgres
snowflake:
  config:
    account: ''
    database: schemapile__github_com_michalbecko_junopubl_d7c58a4576c5
    password: ''
    role: ''
    schema: AIRBYTE_SCHEMA
    username: ''
    warehouse: ''
