Airbyte:
  config:
    custom_api_definition_id: ''
    databricks_definition_id: 072d5540-f236-4294-ba7c-ade8fd918496
    files_definition_id: 778daa7c-feaf-4db6-96f3-70fd645acc77
    mongodb_definition_id: b2e713cd-cc36-4c0a-b5bd-b47cb8a0561e
    namespace_definition: destination
    password: ''
    s3_definition_id: 69589781-7828-43c5-9f63-8925b1c1ccc2
    server_url: http://airbyte-abctl-control-plane:80/api/public/v1/
    username: ''
    workspace_id: ''
aws_s3:
  AWS_ACCESS_KEY_ID: test
  AWS_DEFAULT_REGION: us-west-2
  AWS_ENDPOINT_URL: http://elt-localstack:4566
  AWS_SECRET_ACCESS_KEY: test
  data:
  - path: s3://synsql--3d-spatial-data-analysis-and-monito-79500f84cec4-bucket/alerts.jsonl
    sync_mode: full_refresh_append
    table: alerts
  - path: s3://synsql--3d-spatial-data-analysis-and-monito-79500f84cec4-bucket/calibration_logs.jsonl
    sync_mode: full_refresh_append
    table: calibration_logs
  - path: s3://synsql--3d-spatial-data-analysis-and-monito-79500f84cec4-bucket/roles.jsonl
    sync_mode: full_refresh_append
    table: roles
  - path: s3://synsql--3d-spatial-data-analysis-and-monito-79500f84cec4-bucket/sensors.jsonl
    sync_mode: full_refresh_append
    table: sensors
  - path: s3://synsql--3d-spatial-data-analysis-and-monito-79500f84cec4-bucket/users.jsonl
    sync_mode: full_refresh_append
    table: users
custom_api:
  config:
    configuration: {}
    sync_mode: full_refresh_append
    tables:
    - access_logs
    - neighborhoods
databricks:
  config:
    client_id: ''
    database: ''
    hostname: ''
    http_path: ''
    schema: synsql__3d_spatial_data_analysis_and_monito_79500f84cec4
    secret: ''
flat_files:
- format: csv
  path: http://elt-files:8080/synsql__3d_spatial_data_analysis_and_monito_79500f84cec4/adjustments.csv
  sync_mode: full_refresh_append
  table: adjustments
- format: csv
  path: http://elt-files:8080/synsql__3d_spatial_data_analysis_and_monito_79500f84cec4/reports.csv
  sync_mode: full_refresh_append
  table: reports
mongodb:
  config:
    connection_string: mongodb://elt-mongodb:27017/?directConnection=true
    database: synsql__3d_spatial_data_analysis_and_monito_79500f84cec4
    sync_mode: full_refresh_append
    tables:
    - cells
    - sensor_readings
    - sensor_types
    - user_roles
